[Service]
ExecStart=
ExecStart=/bin/bash -c "source /opt/ros/humble/setup.bash && source /home/jetson/pingpong/ros2_ws/install/setup.bash && export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda-12.6/lib64:$$LD_LIBRARY_PATH && ros2 run pingpong_detect pingpong_detect_graph_node --ros-args -p config_path:=/home/jetson/unitree_rl_lab_lgy/deploy/robots/a1_h1/jetson_camera/detect_config_a1_backhand.yaml"
